Appy.Configuration:
  Type: Package
Appy.Configuration.WinRegistry:
  Type: Package
Appy.Infrastructure.1Password:
  Type: Package
Appy.Configuration.1Password:
  Type: Package
Appy.Tool.1Password:
  Type: Package
Appy.Configuration.WinRegistry.Tests:
  Type: XUnit
Appy.Infrastructure.1Password.Tests:
  Type: XUnit
Appy.Configuration.1Password.Tests:
  Type: XUnit
Appy.Tool.1Password.Tests:
  Type: XUnit